project:
  type: website

website:
  title: "ahanasamat.github.io"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - href: assignment1.html
        text: Assignment 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

